[package]
name = "puniyu_plugin"
version = "0.2.1"
description = "puniyu 的插件模块"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
serde_json.workspace = true
inventory.workspace = true
puniyu_logger.workspace = true


puniyu_builder = { workspace = true, features = ["plugin"] }
puniyu_command = { workspace = true, features = ["registry"] }
puniyu_adapter_api = { workspace = true }
puniyu_element = { workspace = true }
puniyu_event = { workspace = true }
puniyu_common = { workspace = true }
puniyu_macros = { workspace = true, features = ["plugin"] }
puniyu_contact = { workspace = true }
