[package]
name = "puniyu_plugin"
version = "0.5.7"
description = "puniyu 的插件模块"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
serde_json.workspace = true
toml.workspace = true
inventory.workspace = true
puniyu_logger.workspace = true
actix-web.workspace = true

puniyu_common = { version = "0.5.7", path = "../../crates/puniyu_common" }
puniyu_macros = { version = "0.5.7", path = "../../crates/puniyu_macros", features = [
  "plugin",
] }
puniyu_types = { version = "0.5.7", path = "../../crates/puniyu_types", default-features = false, features = [
  "plugin",
  "event",
] }
puniyu_registry = { version = "0.5.7", path = "../../crates/puniyu_registry", default-features = false, features = [
  "plugin",
] }
