[package]
name = "puniyu_plugin"
version = "0.4.1"
description = "puniyu 的插件模块"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
serde_json.workspace = true
inventory.workspace = true
puniyu_logger.workspace = true


puniyu_builder = { version = "0.4.1", path = "../../crates/puniyu_builder", features = ["plugin"] }
puniyu_command = { version = "0.4.1", path = "../../crates/puniyu_command", features = ["registry"] }
puniyu_adapter_api = { version = "0.4.1", path = "../../crates/puniyu_adapter_api" }
puniyu_element = { version = "0.4.1", path = "../../crates/puniyu_element" }
puniyu_event = { version = "0.4.1", path = "../../crates/puniyu_event" }
puniyu_common = { version = "0.4.1", path = "../../crates/puniyu_common" }
puniyu_macros = { version = "0.4.1", path = "../../crates/puniyu_macros", features = ["plugin"] }
puniyu_contact = { version = "0.4.1", path = "../../crates/puniyu_contact" }
