[package]
name = "puniyu_protocol"
version = "0.1.0"
description = "puniyu 协议库，用于数据交换"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
include = ["src", "protos", "Cargo.toml", "build.rs"]

[dependencies]
prost.workspace = true
bytes.workspace = true
chrono.workspace = true
puniyu_types = { version = "0.6.0", path = "../../crates/puniyu_types" }


[build-dependencies]
glob.workspace = true
prost-build = "0.14.1"
protoc-bin-vendored = "3.2.0"
