[package]
name = "puniyu_command"
version = "0.4.0"
description = "puniyu 的命令相关"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
itertools = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }
puniyu_event = { version = "0.4.0", path = "../puniyu_event", features = ["context"], optional = true }

[features]
default = ["builder"]
builder = ["dep:async-trait", "dep:puniyu_event"]
registry = ["dep:itertools", "builder"]
