[package]
name = "puniyu_command"
version = "0.7.8"
description = "puniyu的命令处理器"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
puniyu_logger.workspace = true
thiserror.workspace = true
clap = { workspace = true, features = ["string", "error-context"] }
itertools.workspace = true

puniyu_config = { version = "0.7.5", path = "../puniyu_config" }
puniyu_registry = { version = "0.7.8", path = "../puniyu_registry", default-features = false, features = [
    "command",
    "cooldown",
    "bot"
] }
puniyu_types = { version = "0.7.6", path = "../puniyu_types", default-features = false, features = [
    "handler",
    "element",
    "event",
] }

