[workspace]
members = [
    "crates/*",
    "adapters/*",
    "puniyu",
    "puniyu_core",
    "puniyu_plugin",
    "puniyu_adapter",
]
resolver = "2"

[workspace.package]
authors = ["wuliya <3369906077@qq.com>"]
license = "LGPL-3.0-only"
readme = "README.md"
homepage = "https://github.com/puniyu/puniyu"
repository = "https://github.com/puniyu/puniyu"
edition = "2024"
rust-version = "1.88.0"

[workspace.dependencies]
chrono = { version = "0.4" }
tokio = { version = "1.47.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0"}
itertools = { version = "0.14.0" }
futures = { version = "0.3.31" }
async-trait = { version = "0.1.89" }
thiserror = { version = "2.0.16" }
inventory = "0.3.21"
strum = { version = "0.27.2", features = ["derive"] }
convert_case = { version = "0.9.0" }
actix-web = "4.11.0"
reqwest = { version = "0.12.24", default-features = false, features = ["json", "rustls-tls"] }

puniyu_bot = { version = "0.1.8", path = "crates/puniyu_bot" }
puniyu_adapter_api = { version = "0.1.8", path = "crates/puniyu_adapter_api" }
puniyu_element = { version = "0.1.8", path = "crates/puniyu_element" }
puniyu_contact = { version = "0.1.8", path = "crates/puniyu_contact" }
puniyu_sender = { version = "0.1.8", path = "crates/puniyu_sender" }
puniyu_builder = { version = "0.1.8", path = "crates/puniyu_builder", default-features = false }
puniyu_command = { version = "0.1.8", path = "crates/puniyu_command", default-features = false }
puniyu_common = { version = "0.1.8", path = "crates/puniyu_common" }
puniyu_config = { version = "0.1.8", path = "crates/puniyu_config" }
puniyu_library = { version = "0.1.8", path = "crates/puniyu_library" }
puniyu_task = { version = "0.1.8", path = "crates/puniyu_task" }
puniyu_event = { version = "0.1.8", path = "crates/puniyu_event", default-features = false }
puniyu_matcher = { version = "0.1.8", path = "crates/puniyu_matcher" }
puniyu_event_bus = { version = "0.1.8", path = "crates/puniyu_event_bus", default-features = false }
puniyu_handler = { version = "0.1.8", path = "crates/puniyu_handler" }
puniyu_macros = { version = "0.1.8", path = "crates/puniyu_macros", default-features = false }
puniyu_registry = { version = "0.1.8", path = "crates/puniyu_registry" }
puniyu_server = { version = "0.1.8", path = "crates/puniyu_server", default-features = false }

puniyu_logger = { version = "0.6.1" }


[profile.release]
lto = "thin"
incremental = false

[profile.dev]
incremental = true

