[workspace]
members = [
    "puniyu",
    "puniyu_core",
    "puniyu_logger", 
    "puniyu_macro", 
    "puniyu_plugin_test",
    "puniyu_registry",
    "puniyu_utils",
]
resolver = "2"

[workspace.package]
authors = ["wuliya <3369906077@qq.com>"]
license = "LGPL-3.0-only"
readme = "README.md"
homepage = "https://github.com/Puniyu/core"
repository = "https://github.com/Puniyu/core"
edition = "2024"
rust-version = "1.88.0"

[workspace.dependencies]
chrono = { version = "0.4" }
log = { version = "0.4.27" }
tokio = { version = "1.47.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0"}
lazy_static = { version = "1.5.0" }


[workspace.lints.clippy]
uninlined_format_args = "allow"

[profile.release]
lto = "thin"
panic = "abort"
incremental = false

[profile.dev]
incremental = true
