[workspace]
members = [
    "crates/*",
    "packages/*",
    "adapters/*"
]
resolver = "2"

[workspace.package]
authors = ["wuliya <3369906077@qq.com>"]
license = "LGPL-3.0-only"
readme = "README.md"
homepage = "https://github.com/puniyu/puniyu"
repository = "https://github.com/puniyu/puniyu"
edition = "2024"
rust-version = "1.88.0"

[workspace.dependencies]
chrono = { version = "0.4" }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0"}
toml = { version = "0.9.5" }
itertools = { version = "0.14.0" }
futures = { version = "0.3.31" }
async-trait = { version = "0.1.89" }
thiserror = { version = "2.0.17" }
inventory = "0.3.21"
strum = { version = "0.27.2", features = ["derive"] }
convert_case = { version = "0.9.0" }
actix-web = "4.11.0"
reqwest = { version = "0.12.24", default-features = false, features = ["json", "rustls-tls"] }

puniyu_logger = { version = "0.6.2" }

[profile.release]
lto = "thin"
incremental = false

[profile.dev]
incremental = true

