[package]
name = "puniyu_common"
version = "0.7.5"
description = "puniyu 的通用库"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
toml = { workspace = true }
strum.workspace = true
puniyu_system_info = { workspace = true, optional = true }

serde.workspace = true
thiserror.workspace = true

[features]
default = ["version"]
version = []
system-info = ["dep:puniyu_system_info"]
