[package]
name = "puniyu_macros"
version = "0.5.13"
description = "puniyu 的属性宏库"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.106", features = ["full"] }
proc-macro2 = { version = "1.0.101" }
quote = { version = "1.0.40" }
croner = { version = "3.0.0" }

convert_case.workspace = true


[features]
default = ["plugin"]
adapter = []
plugin = ["task", "command"]
command = []
task = []
