[package]
name = "puniyu_adapter_console"
version = "0.1.10"
description = "puniyu的控制台适配器"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
rand = "0.10.0-rc.0"
puniyu_adapter = { version = "0.2.2", path = "../puniyu_adapter" }
puniyu_core = { version = "0.3.1", path = "../puniyu_core" }
puniyu_common = { version = "0.3.0", path = "../../crates/puniyu_common" }

[build-dependencies]
puniyu_build = { version = "0.2.0", path = "../../crates/puniyu_build" }
