[package]
name = "puniyu_adapter_console"
version = "0.1.9"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
rand = "0.10.0-rc.0"
puniyu_adapter = { workspace = true }
puniyu_core = { workspace = true }
puniyu_common = { path = "../../crates/puniyu_common" }

[build-dependencies]
puniyu_build = { workspace = true }
