[package]
name = "puniyu_adapter_console"
<<<<<<< Updated upstream
version = "0.4.1"
=======
version = "0.4.3"
>>>>>>> Stashed changes
description = "puniyu的控制台适配器"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
rand = "0.9.2"
<<<<<<< Updated upstream
puniyu_adapter = { version = "0.7.4", path = "../../packages/puniyu_adapter" }
puniyu_core = { version = "0.7.4", path = "../../packages/puniyu_core" }
=======
puniyu_adapter = { version = "0.7.6", path = "../../packages/puniyu_adapter" }
puniyu_core = { version = "0.7.6", path = "../../packages/puniyu_core" }
>>>>>>> Stashed changes
