[package]
name = "puniyu_server"
version = "0.4.1"
description = "puniyu 的服务器模块"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "puniyu_server"
path = "src/main.rs"

[dependencies]
puniyu_logger.workspace = true
tokio.workspace = true
actix-web.workspace = true
futures-util = "0.3.31"

puniyu_registry = { version = "0.4.1", path = "../puniyu_registry", default-features = false, features = ["server"] }
