[package]
name = "puniyu_types"
version = "0.1.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
strum = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
toml = { version = "0.9.5", optional = true }
puniyu_system_info = { version = "0.8.0", features = ["gpu"], optional = true }
reqwest = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }

[features]
default = []
adapter = [
    "dep:thiserror",
    "dep:reqwest",
    "dep:async-trait",
    "contact",
    "sender",
    "element",
]
contact = ["dep:serde", "dep:strum"]
sender = ["dep:serde", "dep:strum"]
element = ["dep:serde", "dep:strum", "dep:serde_json"]
common = ["dep:thiserror", "dep:toml", "dep:puniyu_system_info"]
