[package]
name = "puniyu_core"
version = "0.6.0"
description = "puniyu 的核心模块，包含基础设施和通用功能"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
include = ["src", "Cargo.toml", "README.md", "build.rs", "assets"]

[dependencies]
figlet-rs = "0.1.5"
glob = "0.3.3"

thiserror.workspace = true
tokio.workspace = true
async-trait.workspace = true
inventory.workspace = true
convert_case.workspace = true

puniyu_system_info.workspace = true

puniyu_logger = { workspace = true, optional = true }
puniyu_server = { version = "0.6.0", path = "../puniyu_server", optional = true, default-features = false }
puniyu_config = { version = "0.6.0", path = "../../crates/puniyu_config" }
puniyu_bus = { version = "0.6.0", path = "../../crates/puniyu_bus" }
puniyu_common = { version = "0.6.0", path = "../../crates/puniyu_common" }
puniyu_types = { version = "0.6.0", path = "../../crates/puniyu_types" }
puniyu_registry = { version = "0.6.0", path = "../../crates/puniyu_registry" }

[features]
default = ["server", "logger"]
server = ["dep:puniyu_server"]
logger = ["dep:puniyu_logger"]
stable = ["puniyu_common/stable"]

