[package]
name = "puniyu_core"
version = "0.7.7"
description = "puniyu 的核心模块，包含基础设施和通用功能"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
include = ["src", "Cargo.toml", "README.md", "assets"]

[dependencies]
figlet-rs = "0.1.5"
bytes.workspace = true
glob.workspace = true
thiserror.workspace = true
tokio.workspace = true
async-trait.workspace = true
inventory.workspace = true
convert_case.workspace = true
puniyu_system_info.workspace = true

puniyu_logger = { workspace = true, optional = true }
puniyu_server = { version = "0.7.7", path = "../puniyu_server", optional = true, default-features = false }
puniyu_config = { version = "0.7.5", path = "../../crates/puniyu_config" }
puniyu_event = { version = "0.7.7", path = "../../crates/puniyu_event" }
puniyu_common = { version = "0.7.5", path = "../../crates/puniyu_common" }
puniyu_types = { version = "0.7.6", path = "../../crates/puniyu_types" }
puniyu_registry = { version = "0.7.8", path = "../../crates/puniyu_registry" }

[features]
default = ["server", "logger"]
server = ["dep:puniyu_server"]
logger = ["dep:puniyu_logger"]

