[package]
name = "puniyu_core"
version = "0.3.0"
description = "puniyu 的核心模块，包含基础设施和通用功能"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
figlet-rs = "0.1.5"
glob = "0.3.3"

thiserror.workspace = true
tokio.workspace = true
async-trait.workspace = true
inventory.workspace = true
convert_case.workspace = true

puniyu_logger = { workspace = true, optional = true }
puniyu_config = { version = "0.2.0", path = "../../crates/puniyu_config" }
puniyu_bot = { version = "0.2.0", path = "../../crates/puniyu_bot" }
puniyu_task = { version = "0.1.9", path = "../../crates/puniyu_task" }
puniyu_server = { version = "0.2.0", path = "../../crates/puniyu_server", optional = true }
puniyu_builder = { version = "0.2.0", path = "../../crates/puniyu_builder", features = ["plugin"] }
puniyu_registry = { version = "0.2.0", path = "../../crates/puniyu_registry", features = ["plugin", "adapter"] }
puniyu_common = { version = "0.2.0", path = "../../crates/puniyu_common" }
puniyu_event_bus = { version = "0.2.0", path = "../../crates/puniyu_event_bus" }

[features]
default = ["server", "logger"]
server = ["dep:puniyu_server"]
logger = ["dep:puniyu_logger"]

