[package]
name = "puniyu_config"
version = "0.5.7"
description = "puniyu 配置模块"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
toml.workspace = true
puniyu_logger.workspace = true
serde.workspace = true

puniyu_common = { version = "0.5.7", path = "../puniyu_common" }
notify-debouncer-mini = { version = "0.7.0", features = ["flume"] }

