[package]
name = "puniyu_matcher_command"
version = "0.7.0"
description = "Puniyu Matcher Command"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
puniyu_logger.workspace = true

puniyu_config = { version = "0.7.0", path = "../puniyu_config" }
puniyu_registry = { version = "0.7.0", path = "../puniyu_registry", default-features = false, features = ["command"] }
puniyu_types = { version = "0.7.0", path = "../puniyu_types", default-features = false, features = ["matcher", "element", "event"] }
