[package]
name = "puniyu_adapter"
version = "0.5.7"
description = "puniyu 的适配器模块"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
inventory.workspace = true
puniyu_logger.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
actix-web.workspace = true
convert_case.workspace = true

puniyu_config = { version = "0.5.7", path = "../../crates/puniyu_config" }
puniyu_macros = { version = "0.5.7", path = "../../crates/puniyu_macros", features = [
  "adapter",
] }
puniyu_common = { version = "0.5.7", path = "../../crates/puniyu_common" }
puniyu_types = { version = "0.5.7", path = "../../crates/puniyu_types", default-features = false, features = [
  "adapter",
  "event",
  "bot",
] }
puniyu_registry = { version = "0.5.7", path = "../../crates/puniyu_registry", default-features = false, features = [
  "adapter",
] }
puniyu_bus = { version = "0.4.10", path = "../../crates/puniyu_bus" }
