[package]
name = "puniyu_bot"
version = "0.2.0"
description = "puniyu 的bot相关"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
puniyu_logger.workspace = true

puniyu_common = { version = "0.2.0", path = "../puniyu_common" }
puniyu_element = { version = "0.2.0", path = "../puniyu_element" }
puniyu_adapter_api = { version = "0.2.0", path = "../puniyu_adapter_api" }
puniyu_contact = { version = "0.1.9", path = "../puniyu_contact" }
puniyu_builder = { version = "0.2.0", path = "../puniyu_builder", features = ["adapter"] }
