[package]
name = "puniyu_adapter_server"
<<<<<<< Updated upstream
version = "0.3.2"
=======
version = "0.3.4"
>>>>>>> Stashed changes
description = "puniyu的server适配器"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
thiserror.workspace = true
prost.workspace = true
actix-web.workspace = true
async-trait.workspace = true
tokio.workspace = true
<<<<<<< Updated upstream
puniyu_adapter = { version = "0.7.4", path = "../../packages/puniyu_adapter" }
puniyu_core = { version = "0.7.4", path = "../../packages/puniyu_core" }
puniyu_protocol = { version = "0.2.1", path = "../../packages/puniyu_protocol" }
=======
puniyu_adapter = { version = "0.7.6", path = "../../packages/puniyu_adapter" }
puniyu_core = { version = "0.7.6", path = "../../packages/puniyu_core" }
puniyu_protocol = { version = "0.2.2", path = "../../packages/puniyu_protocol" }
>>>>>>> Stashed changes
futures-util = "0.3.31"
actix-ws = "0.3.0"

