[package]
name = "puniyu_server"
version = "0.7.5"
description = "puniyu 的服务器模块"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "puniyu_server"
path = "src/main.rs"

[dependencies]
serde.workspace = true
serde_json.workspace = true
puniyu_logger.workspace = true
tokio = { workspace = true, features = ["full"] }
actix-web.workspace = true
futures-util = "0.3.31"
flume.workspace = true
clap = { workspace = true, optional = true, features = ["derive", "help"] }

puniyu_common = { version = "0.7.4", path = "../../crates/puniyu_common" }
puniyu_types = { version = "0.7.4", path = "../../crates/puniyu_types", default-features = false, features = [
  "server",
] }
puniyu_registry = { version = "0.7.5", path = "../../crates/puniyu_registry", default-features = false, features = [
  "server",
] }

[features]
default = ["cli"]
cli = ["dep:clap"]

[package.metadata.workspaces]
independent = true
