[package]
name = "puniyu_event"
version = "0.2.0"
description = "puniyu 的事件基础库"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
strum.workspace = true
puniyu_element = { version = "0.2.0", path = "../puniyu_element" }
puniyu_adapter_api = { version = "0.2.0", path = "../puniyu_adapter_api", optional = true }
puniyu_sender = { version = "0.1.9", path = "../puniyu_sender", optional = true }
puniyu_contact = { version = "0.1.9", path = "../puniyu_contact", optional = true }
puniyu_config = { version = "0.2.0", path = "../puniyu_config", optional = true }

[features]
default = []
event = ["message", "notion", "request"]
context = ["event", "dep:puniyu_config", "dep:puniyu_adapter_api"]
message = ["dep:puniyu_sender", "dep:puniyu_contact", "event"]
notion = ["dep:puniyu_sender", "dep:puniyu_contact", "dep:puniyu_adapter_api"]
request = ["dep:puniyu_sender", "dep:puniyu_contact"]
