[package]
name = "puniyu_event"
version = "0.7.4"
description = "puniyu 事件总线库"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
puniyu_logger.workspace = true
tokio = { workspace = true, features = ["macros"] }
puniyu_types = { version = "0.7.4", path = "../puniyu_types", default-features = false, features = [
  "bus",
  "handler",
] }
puniyu_command = { version = "0.7.4", path = "../puniyu_command" }
puniyu_registry = { version = "0.7.4", path = "../puniyu_registry", default-features = false, features = [
  "handler",
] }

[package.metadata.workspaces]
independent = true
