[package]
name = "puniyu_event_bus"
version = "0.4.0"
description = "puniyu 的事件总线处理库"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
strum.workspace = true
tokio.workspace = true
puniyu_logger.workspace = true

puniyu_adapter_api = { version = "0.4.0", path = "../puniyu_adapter_api" }
puniyu_matcher = { version = "0.4.0", path = "../puniyu_matcher" }
puniyu_handler = { version = "0.4.0", path = "../puniyu_handler" }
puniyu_event = { version = "0.4.0", path = "../puniyu_event", features = ["context"] }

