[package]
name = "puniyu_matcher"
version = "0.3.0"
description = "puniyu 的事件匹配器模块"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
puniyu_logger.workspace = true

puniyu_element = { version = "0.3.0", path = "../puniyu_element" }
puniyu_event = { version = "0.3.0", path = "../puniyu_event", features = ["message"] }
