[package]
name = "puniyu"
version = "0.5.8"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
puniyu_core = { path = "../puniyu_core" }
puniyu_adapter_console = { path = "../../adapters/console" }

[[bin]]
name = "puniyu"
path = "src/main.rs"

