[package]
name = "puniyu"
version = "0.7.8"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
puniyu_core = { version = "0.7.8", path = "../puniyu_core" }
puniyu_adapter_console = { version = "0.4.5", path = "../../adapters/puniyu_adapter_console" }
puniyu_adapter_server = { version = "0.3.6", path = "../../adapters/puniyu_adapter_server" }
puniyu_plugin_basic = { version = "0.2.5", path = "../../plugins/puniyu_plugin_basic" }

[[bin]]
name = "puniyu"
path = "src/main.rs"

[features]
default = []
