[package]
name = "puniyu"
version = "0.6.0"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
puniyu_core = { path = "../puniyu_core" }
puniyu_adapter_console = { path = "../../adapters/puniyu_adapter_console" }
puniyu_plugin_basic = { path = "../../plugins/puniyu_plugin_basic" }

[[bin]]
name = "puniyu"
path = "src/main.rs"

[features]
default = []
