[package]
name = "puniyu_adapter_api"
version = "0.2.0"
description = "puniyu 的适配器api"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
serde.workspace = true
reqwest.workspace = true
tokio.workspace = true

puniyu_common = { version = "0.2.0", path = "../puniyu_common" }
puniyu_contact = { version = "0.1.9", path = "../puniyu_contact" }
puniyu_sender = { version = "0.1.9", path = "../puniyu_sender" }
puniyu_element = { version = "0.2.0", path = "../puniyu_element" }

