[package]
name = "puniyu_hook"
version = "0.1.3"
description = "puniyu 的钩子处理器"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
puniyu_logger.workspace = true
async-trait.workspace = true
puniyu_types = { version = "0.7.8", path = "../puniyu_types", default-features = false, features = [
    "handler",
    "element",
    "event",
    "server"
] }
puniyu_registry = { version = "0.7.10", path = "../puniyu_registry", default-features = false, features = [
    "hook",
] }
